# This file has been generated by node2nix-hs 0.0.1. Do not edit!

{ nodeEnv
  , fetchurl
  , fetchgit
  , nix-gitignore
  , stdenv
  , lib
  , globalBuildInputs ? [] }:
  let
    sources = {
      "@babel/runtime-7.23.2" = {
        name = "_at_babel_slash_runtime";
        packageName = "@babel/runtime";
        version = "7.23.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.23.2.tgz";
          sha512 = "mM8eg4yl5D6i3lu2QKPuPH4FArvJ8KhTofbE7jwMUv9KX5mBvwPAqnV3MlyBNqdp9RyRKP6Yck8TrfYrPvX3bg==";
          };
        };
      "@floating-ui/core-1.5.0" = {
        name = "_at_floating-ui_slash_core";
        packageName = "@floating-ui/core";
        version = "1.5.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/@floating-ui/core/-/core-1.5.0.tgz";
          sha512 = "kK1h4m36DQ0UHGj5Ah4db7R0rHemTqqO0QLvUqi1/mUUp3LuAWbWxdxSIf/XsnH9VS6rRVPLJCncjRzUvyCLXg==";
          };
        };
      "@floating-ui/dom-1.5.3" = {
        name = "_at_floating-ui_slash_dom";
        packageName = "@floating-ui/dom";
        version = "1.5.3";
        src = fetchurl {
          url = "https://registry.npmjs.org/@floating-ui/dom/-/dom-1.5.3.tgz";
          sha512 = "ClAbQnEqJAKCJOEbbLo5IUlZHkNszqhuxS4fHAVxRPXPya6Ysf2G8KypnYcOTpx6I8xcgF9bbHb6g/2KpbV8qA==";
          };
        };
      "@floating-ui/react-0.24.8" = {
        name = "_at_floating-ui_slash_react";
        packageName = "@floating-ui/react";
        version = "0.24.8";
        src = fetchurl {
          url = "https://registry.npmjs.org/@floating-ui/react/-/react-0.24.8.tgz";
          sha512 = "AuYeDoaR8jtUlUXtZ1IJ/6jtBkGnSpJXbGNzokBL87VDJ8opMq1Bgrc0szhK482ReQY6KZsMoZCVSb4xwalkBA==";
          };
        };
      "@floating-ui/react-dom-2.0.2" = {
        name = "_at_floating-ui_slash_react-dom";
        packageName = "@floating-ui/react-dom";
        version = "2.0.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/@floating-ui/react-dom/-/react-dom-2.0.2.tgz";
          sha512 = "5qhlDvjaLmAst/rKb3VdlCinwTF4EYMiVxuuc/HVUjs46W0zgtbMmAZ1UTsDrRTxRmUEzl92mOtWbeeXL26lSQ==";
          };
        };
      "@floating-ui/utils-0.1.6" = {
        name = "_at_floating-ui_slash_utils";
        packageName = "@floating-ui/utils";
        version = "0.1.6";
        src = fetchurl {
          url = "https://registry.npmjs.org/@floating-ui/utils/-/utils-0.1.6.tgz";
          sha512 = "OfX7E2oUDYxtBvsuS4e/jSn4Q9Qb6DzgeYtsAdkPZ47znpoNsMgZw0+tVijiv3uGNR6dgNlty6r9rzIzHjtd/A==";
          };
        };
      "@mantine/core-7.2.2" = {
        name = "_at_mantine_slash_core";
        packageName = "@mantine/core";
        version = "7.2.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/@mantine/core/-/core-7.2.2.tgz";
          sha512 = "cVGmLjYyKIzjn0LRwamj71O4HT43qCxPGAzMZqkMYGOako7xwBLYQNe7HjL/J0FXJDyfX8OdMylVhgsePWYbng==";
          };
        };
      "@mantine/dates-7.2.2" = {
        name = "_at_mantine_slash_dates";
        packageName = "@mantine/dates";
        version = "7.2.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/@mantine/dates/-/dates-7.2.2.tgz";
          sha512 = "MgUy2qODhXEkdK5OQE3talThrbXKfBK6V0AJ8iwPcrxMoQ77u4aMzTv4+47bEjQeUFyjrT8u916VFd82mn59SA==";
          };
        };
      "@mantine/hooks-7.2.2" = {
        name = "_at_mantine_slash_hooks";
        packageName = "@mantine/hooks";
        version = "7.2.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/@mantine/hooks/-/hooks-7.2.2.tgz";
          sha512 = "7CFSVP2aQHrBwLLAVf0q5dgj+6QTZmhLTNcuc3pE1du+HLFUdyVS6vvQC6kieZXxOd6UzwFGBlN4G+aDx95XeA==";
          };
        };
      "aria-hidden-1.2.3" = {
        name = "aria-hidden";
        packageName = "aria-hidden";
        version = "1.2.3";
        src = fetchurl {
          url = "https://registry.npmjs.org/aria-hidden/-/aria-hidden-1.2.3.tgz";
          sha512 = "xcLxITLe2HYa1cnYnwCjkOO1PqUHQpozB8x9AR0OgWN2woOBi5kSDVxKfd0b7sb1hw5qFeJhXm9H1nu3xSfLeQ==";
          };
        };
      "clsx-2.0.0" = {
        name = "clsx";
        packageName = "clsx";
        version = "2.0.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/clsx/-/clsx-2.0.0.tgz";
          sha512 = "rQ1+kcj+ttHG0MKVGBUXwayCCF1oh39BF5COIpRzuCEv8Mwjv0XucrI2ExNTOn9IlLifGClWQcU9BrZORvtw6Q==";
          };
        };
      "dayjs-1.11.10" = {
        name = "dayjs";
        packageName = "dayjs";
        version = "1.11.10";
        src = fetchurl {
          url = "https://registry.npmjs.org/dayjs/-/dayjs-1.11.10.tgz";
          sha512 = "vjAczensTgRcqDERK0SR2XMwsF/tSvnvlv6VcF2GIhg6Sx4yOIt/irsr1RDJsKiIyBzJDpCoXiWWq28MqH2cnQ==";
          };
        };
      "detect-node-es-1.1.0" = {
        name = "detect-node-es";
        packageName = "detect-node-es";
        version = "1.1.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/detect-node-es/-/detect-node-es-1.1.0.tgz";
          sha512 = "ypdmJU/TbBby2Dxibuv7ZLW3Bs1QEmM7nHjEANfohJLvE0XVujisn1qPJcZxg+qDucsr+bP6fLD1rPS3AhJ7EQ==";
          };
        };
      "get-nonce-1.0.1" = {
        name = "get-nonce";
        packageName = "get-nonce";
        version = "1.0.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/get-nonce/-/get-nonce-1.0.1.tgz";
          sha512 = "FJhYRoDaiatfEkUK8HKlicmu/3SGFD51q3itKDGoSTysQJBnfOcxU5GxnhE1E6soB76MbT0MBtnKJuXyAx+96Q==";
          };
        };
      "invariant-2.2.4" = {
        name = "invariant";
        packageName = "invariant";
        version = "2.2.4";
        src = fetchurl {
          url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
          sha512 = "phJfQVBuaJM5raOpJjSfkiD6BpbCE4Ns//LaXl6wGYtUBY83nWS6Rf9tXm2e8VaK60JEjYldbPif/A2B1C2gNA==";
          };
        };
      "js-tokens-4.0.0" = {
        name = "js-tokens";
        packageName = "js-tokens";
        version = "4.0.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
          sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
          };
        };
      "loose-envify-1.4.0" = {
        name = "loose-envify";
        packageName = "loose-envify";
        version = "1.4.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
          sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
          };
        };
      "object-assign-4.1.1" = {
        name = "object-assign";
        packageName = "object-assign";
        version = "4.1.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
          sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
          };
        };
      "prop-types-15.8.1" = {
        name = "prop-types";
        packageName = "prop-types";
        version = "15.8.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz";
          sha512 = "oj87CgZICdulUohogVAR7AjlC0327U4el4L6eAvOqCeudMDVU0NThNaV+b9Df4dXgSP1gXMTnPdhfe/2qDH5cg==";
          };
        };
      "react-18.2.0" = {
        name = "react";
        packageName = "react";
        version = "18.2.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/react/-/react-18.2.0.tgz";
          sha512 = "/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==";
          };
        };
      "react-dom-18.2.0" = {
        name = "react-dom";
        packageName = "react-dom";
        version = "18.2.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-dom/-/react-dom-18.2.0.tgz";
          sha512 = "6IMTriUmvsjHUjNtEDudZfuDQUoWXVxKHhlEGSk81n4YFS+r/Kl99wXiwlVXtPBtJenozv2P+hxDsw9eA7Xo6g==";
          };
        };
      "react-icons-4.7.1" = {
        name = "react-icons";
        packageName = "react-icons";
        version = "4.7.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-icons/-/react-icons-4.7.1.tgz";
          sha512 = "yHd3oKGMgm7zxo3EA7H2n7vxSoiGmHk5t6Ou4bXsfcgWyhfDKMpyKfhHR6Bjnn63c+YXBLBPUql9H4wPJM6sXw==";
          };
        };
      "react-is-16.13.1" = {
        name = "react-is";
        packageName = "react-is";
        version = "16.13.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
          sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
          };
        };
      "react-number-format-5.3.1" = {
        name = "react-number-format";
        packageName = "react-number-format";
        version = "5.3.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-number-format/-/react-number-format-5.3.1.tgz";
          sha512 = "qpYcQLauIeEhCZUZY9jXZnnroOtdy3jYaS1zQ3M1Sr6r/KMOBEIGNIb7eKT19g2N1wbYgFgvDzs19hw5TrB8XQ==";
          };
        };
      "react-remove-scroll-2.5.7" = {
        name = "react-remove-scroll";
        packageName = "react-remove-scroll";
        version = "2.5.7";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-remove-scroll/-/react-remove-scroll-2.5.7.tgz";
          sha512 = "FnrTWO4L7/Bhhf3CYBNArEG/yROV0tKmTv7/3h9QCFvH6sndeFf1wPqOcbFVu5VAulS5dV1wGT3GZZ/1GawqiA==";
          };
        };
      "react-remove-scroll-bar-2.3.4" = {
        name = "react-remove-scroll-bar";
        packageName = "react-remove-scroll-bar";
        version = "2.3.4";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-remove-scroll-bar/-/react-remove-scroll-bar-2.3.4.tgz";
          sha512 = "63C4YQBUt0m6ALadE9XV56hV8BgJWDmmTPY758iIJjfQKt2nYwoUrPk0LXRXcB/yIj82T1/Ixfdpdk68LwIB0A==";
          };
        };
      "react-style-singleton-2.2.1" = {
        name = "react-style-singleton";
        packageName = "react-style-singleton";
        version = "2.2.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-style-singleton/-/react-style-singleton-2.2.1.tgz";
          sha512 = "ZWj0fHEMyWkHzKYUr2Bs/4zU6XLmq9HsgBURm7g5pAVfyn49DgUiNgY2d4lXRlYSiCif9YBGpQleewkcqddc7g==";
          };
        };
      "react-textarea-autosize-8.5.3" = {
        name = "react-textarea-autosize";
        packageName = "react-textarea-autosize";
        version = "8.5.3";
        src = fetchurl {
          url = "https://registry.npmjs.org/react-textarea-autosize/-/react-textarea-autosize-8.5.3.tgz";
          sha512 = "XT1024o2pqCuZSuBt9FwHlaDeNtVrtCXu0Rnz88t1jUGheCLa3PhjE1GH8Ctm2axEtvdCl5SUHYschyQ0L5QHQ==";
          };
        };
      "regenerator-runtime-0.14.0" = {
        name = "regenerator-runtime";
        packageName = "regenerator-runtime";
        version = "0.14.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.14.0.tgz";
          sha512 = "srw17NI0TUWHuGa5CFGGmhfNIeja30WMBfbslPNhf6JrqQlLN5gcrvig1oqPxiVaXb0oW0XRKtH6Nngs5lKCIA==";
          };
        };
      "scheduler-0.23.0" = {
        name = "scheduler";
        packageName = "scheduler";
        version = "0.23.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/scheduler/-/scheduler-0.23.0.tgz";
          sha512 = "CtuThmgHNg7zIZWAXi3AsyIzA3n4xx7aNyjwC2VJldO2LMVDhFK+63xGqq6CsJH4rTAt6/M+N4GhZiDYPx9eUw==";
          };
        };
      "tabbable-6.2.0" = {
        name = "tabbable";
        packageName = "tabbable";
        version = "6.2.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/tabbable/-/tabbable-6.2.0.tgz";
          sha512 = "Cat63mxsVJlzYvN51JmVXIgNoUokrIaT2zLclCXjRd8boZ0004U4KCs/sToJ75C6sdlByWxpYnb5Boif1VSFew==";
          };
        };
      "tslib-2.6.2" = {
        name = "tslib";
        packageName = "tslib";
        version = "2.6.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/tslib/-/tslib-2.6.2.tgz";
          sha512 = "AEYxH93jGFPn/a2iVAwW87VuUIkR1FVUKB77NwMF7nBTDkDrrT/Hpt/IrCJ0QXhW27jTBDcf5ZY7w6RiqTMw2Q==";
          };
        };
      "type-fest-3.13.1" = {
        name = "type-fest";
        packageName = "type-fest";
        version = "3.13.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/type-fest/-/type-fest-3.13.1.tgz";
          sha512 = "tLq3bSNx+xSpwvAJnzrK0Ep5CLNWjvFTOp71URMaAEWBfRb9nnJiBoUe0tF8bI4ZFO3omgBR6NvnbzVUT3Ly4g==";
          };
        };
      "use-callback-ref-1.3.0" = {
        name = "use-callback-ref";
        packageName = "use-callback-ref";
        version = "1.3.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/use-callback-ref/-/use-callback-ref-1.3.0.tgz";
          sha512 = "3FT9PRuRdbB9HfXhEq35u4oZkvpJ5kuYbpqhCfmiZyReuRgpnhDlbr2ZEnnuS0RrJAPn6l23xjFg9kpDM+Ms7w==";
          };
        };
      "use-composed-ref-1.3.0" = {
        name = "use-composed-ref";
        packageName = "use-composed-ref";
        version = "1.3.0";
        src = fetchurl {
          url = "https://registry.npmjs.org/use-composed-ref/-/use-composed-ref-1.3.0.tgz";
          sha512 = "GLMG0Jc/jiKov/3Ulid1wbv3r54K9HlMW29IWcDFPEqFkSO2nS0MuefWgMJpeHQ9YJeXDL3ZUF+P3jdXlZX/cQ==";
          };
        };
      "use-isomorphic-layout-effect-1.1.2" = {
        name = "use-isomorphic-layout-effect";
        packageName = "use-isomorphic-layout-effect";
        version = "1.1.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/use-isomorphic-layout-effect/-/use-isomorphic-layout-effect-1.1.2.tgz";
          sha512 = "49L8yCO3iGT/ZF9QttjwLF/ZD9Iwto5LnH5LmEdk/6cFmXddqi2ulF0edxTwjj+7mqvpVVGQWvbXZdn32wRSHA==";
          };
        };
      "use-latest-1.2.1" = {
        name = "use-latest";
        packageName = "use-latest";
        version = "1.2.1";
        src = fetchurl {
          url = "https://registry.npmjs.org/use-latest/-/use-latest-1.2.1.tgz";
          sha512 = "xA+AVm/Wlg3e2P/JiItTziwS7FK92LWrDB0p+hgXloIMuVCeJJ8v6f0eeHyPZaJrM+usM1FkFfbNCrJGs8A/zw==";
          };
        };
      "use-sidecar-1.1.2" = {
        name = "use-sidecar";
        packageName = "use-sidecar";
        version = "1.1.2";
        src = fetchurl {
          url = "https://registry.npmjs.org/use-sidecar/-/use-sidecar-1.1.2.tgz";
          sha512 = "epTbsLuzZ7lPClpz2TyryBfztm7m+28DlEv2ZCQ3MDr5ssiwyOwGH/e5F9CkfWjJ1t4clvI58yF822/GUkjjhw==";
          };
        };
      };
    args = {
      name = "mantine";
      packageName = "mantine";
      src = ./.;
      dependencies = [
        (sources."@babel/runtime-7.23.2")
        (sources."@floating-ui/core-1.5.0")
        (sources."@floating-ui/dom-1.5.3")
        (sources."@floating-ui/react-0.24.8")
        (sources."@floating-ui/react-dom-2.0.2")
        (sources."@floating-ui/utils-0.1.6")
        (sources."@mantine/core-7.2.2")
        (sources."@mantine/dates-7.2.2")
        (sources."@mantine/hooks-7.2.2")
        (sources."aria-hidden-1.2.3")
        (sources."clsx-2.0.0")
        (sources."dayjs-1.11.10")
        (sources."detect-node-es-1.1.0")
        (sources."get-nonce-1.0.1")
        (sources."invariant-2.2.4")
        (sources."js-tokens-4.0.0")
        (sources."loose-envify-1.4.0")
        (sources."object-assign-4.1.1")
        (sources."prop-types-15.8.1")
        (sources."react-18.2.0")
        (sources."react-dom-18.2.0")
        (sources."react-icons-4.7.1")
        (sources."react-is-16.13.1")
        (sources."react-number-format-5.3.1")
        (sources."react-remove-scroll-2.5.7")
        (sources."react-remove-scroll-bar-2.3.4")
        (sources."react-style-singleton-2.2.1")
        (sources."react-textarea-autosize-8.5.3")
        (sources."regenerator-runtime-0.14.0")
        (sources."scheduler-0.23.0")
        (sources."tabbable-6.2.0")
        (sources."tslib-2.6.2")
        (sources."type-fest-3.13.1")
        (sources."use-callback-ref-1.3.0")
        (sources."use-composed-ref-1.3.0")
        (sources."use-isomorphic-layout-effect-1.1.2")
        (sources."use-latest-1.2.1")
        (sources."use-sidecar-1.1.2")
        ];
      buildInputs = globalBuildInputs;
      meta = {};
      production = true;
      bypassCache = true;
      reconstructLock = false;
      };
  in {
    inherit sources args;
    tarball = nodeEnv.buildNodeSourceDist args;
    package = nodeEnv.buildNodePackage args;
    shell = nodeEnv.buildNodeShell args;
    nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
      src = stdenv.mkDerivation {
        name = args.name + "-package-json";
        src = nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
          ] (args.src);
        dontBuild = true;
        installPhase = "mkdir -p $out; cp -r ./* $out;";
        };
      });
    }